import Head from 'next/head'
// import Image from 'next/image' // Don't Use this Property in Static pages. Use img tag instead
import { Inter } from 'next/font/google'
// import Script from 'next/script'
import styles from '@/styles/Home.module.css'
import PopularBlog from '@/components/PopularBlog'
import HomeText from '@/components/HomeText'
import LoadingBar from 'react-top-loading-bar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Home - Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keywords" content="nextjs, hunting coder, coding blog" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src='/sc.js' strategy='lazyOnload'></Script> */}

      <main className='box-border bg-gray-900  w-screen pb-10'>
        <header className="text-gray-400  body-font">
        </header>

        <section className=' w-[90%] min-h-[90vh] max-w-screen-xl mx-auto px-4 py-12 flex flex-wrap items-center justify-between '>
          <HomeText />
        </section>
        <section className="blogpage flex flex-wrap-reverse lg:flex-wrap justify-center lg:justify-between items-center max-w-screen-xl mx-auto px-4 py-12">
          <div className="w-full lg:w-1/2 flex justify-center items-center lg:pr-12 mb-12 lg:mb-0">
            <img src="/blog.jpg" className="rounded-3xl h-auto lg:h-full w-full lg:w-auto mb-8" alt="my-images" />
          </div>
          <div className="w-full lg:w-1/2 sm: mb-10 md:mb-6 lg:mb-0">
            <PopularBlog />
          </div>
        </section>
      </main >
    </>
  )
}


